import Navbar from "@/components/Navbar";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Kanit, Sawarabi_Mincho } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway'
});

export const sawarabiMincho = Sawarabi_Mincho({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sawarabiMincho'
});

export const kanit = Kanit({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-kanit'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
